/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js'


export default function Model(props) {
  const gltf = useLoader(GLTFLoader, 'bat_render.glb')
  return (
    <primitive object={gltf.scene}/>
  );
}

